### ISSUE TITLE
Date encoding and decoding does not compare equal

### ISSUE THREAD

**Issue by Austinpayne** [vapor/sqlite-nio#31]
### Describe the bug

I've noticed that if you insert a date into an SQLite database then read it back out, the date's do not compare equal. It appears to be some precision loss due to `Date`s internal use of `timeIntervalSinceReferenceDate` as it does not happen all the time. However, it can be reliably reproduced using Xcode's "run Repeatedly" feature (see reproducer below).

### To Reproduce

Modify the `testTimestampStorage` test to check for date equality like so and run the test, possibly multiple times using Xcode's "run Repeatedly" feature:

```swift
func testTimestampStorage() throws {
    let conn = try SQLiteConnection.open(storage: .memory, threadPool: self.threadPool, on: self.eventLoop).wait()
    defer { try! conn.close().wait() }

    let date = Date()
    let rows = try conn.query("SELECT ? as date", [date.sqliteData!]).wait()
    XCTAssertEqual(rows[0].column("date"), .float(date.timeIntervalSince1970))
    XCTAssertEqual(
        Date(sqliteData: rows[0].column("date")!),
        date
    )
    XCTAssertEqual(
        Date(sqliteData: rows[0].column("date")!)!.timeIntervalSinceReferenceDate,
        date.timeIntervalSinceReferenceDate
    )
    XCTAssertEqual(Date(sqliteData: rows[0].column("date")!)?.description, date.description)
}
```

You will see the following errors:

<img width="966" alt="Screen Shot 2022-11-03 at 4 18 37 PM" src="https://user-images.githubusercontent.com/7528924/199845152-79e3c30f-8aa7-4016-b147-5cedfd5f2952.png">

The date equality check does not yield useful information but the `timeIntervalSinceReferenceDate` check reveals the underlying issue with precision. Date internally uses `timeIntervalSinceReferenceDate` for equality checking, see: https://github.com/apple/swift-corelibs-foundation/blob/swift-5.7.1-RELEASE/Sources/Foundation/Date.swift#L156

### Expected behavior

When creating a new `Date` in swift then inserting and reading that date to/from the database I would expect that the read date to compare equal to the original.

### Environment

* Vapor Framework version: N/A, reproduces in SQLiteNIO, commit cb114dc718b302070bf95733109375f99b5ab35c (main)
* Vapor Toolbox version: N/A, reproduces in SQLiteNIO
* OS version: macOS 12.6
* Xcode version: 14.0.1

### Additional context

I noticed this originally using plain `fluent-kit` (no Vapor) and traced it down to the SQLiteNIO package but did see it manifest through each level of the SQLite driver (i.e. FluentSQLiteDriver, SQLiteKit, and SQLiteNIO)

**Comment by Austinpayne** [comment]
@0xTim I'm happy to contribute a fix but wondered if you had any input on the approach. My naive thought was to simply round to 6 decimal places (microseconds) in the `Date.init?(sqliteData:)` init, which appears to be what PostgresNIO does.

**Comment by gwynne** [comment]
@Austinpayne Rounding to µs is the correct solution; while `Date` purports to have nanosecond resolution in theory, in practice the actual quantum of clock updates has historically been rather more coarse. The choice of µs as a "reasonably safe" maximum resolution is dictated by the ISO-8601 date time format - also, not only does every platform Swift runs on provide a µs or better clock, six digits of precision is a small enough mantissa not to suffer from rounding issues in the majority of cases (I don't recall offhand if it's immune to rounding error entirely, though I doubt it). IIRC, six digits worth is also the highest datetime precision available in all databases supported by Fluent, for good measure.

All of which is really just background knowledge anyhow 😅 - in any event, a fix that replicates PostgresNIO's behavior would be very welcome 🙂.  Fluent's SQLite support hasn't gotten much attention for awhile now.
