### ISSUE TITLE
`.unsafeFlags` added in release 1.3.2

### ISSUE THREAD

**Issue by klaas** [vapor/sqlite-nio#38]
### Describe the bug

Build error when using `sqlite-nio`:

````
error: the target 'CSQLite' in product 'SQLiteNIO' contains unsafe build flags
error: the target 'CSQLite' in product 'SQLiteKit' contains unsafe build flags
````

### To Reproduce

Create a fresh vapor project and add these dependencies:

````
	.package(url: "https://github.com/vapor/fluent.git", from: "4.6.0"),
	.package(url: "https://github.com/vapor/fluent-sqlite-driver.git", from: "4.2.0"),
````
### Expected behavior

Successful build.

### Environment

* Vapor Framework version:
framework: 4.69.1
* Vapor Toolbox version:
toolbox: 18.6.0
* OS version:
macOS: 13.2 (22D49)

### Additional context

I guess, `.unsafeFlags` cannot be used in versioned dependencies?
See https://stackoverflow.com/questions/66462498/how-to-override-the-unsafeflags-behavior-of-swift-package-manager

**Comment by mkll** [comment]
Same here. Very frustrating because I just made some changes in package list and thought it was because of them.
