### ISSUE TITLE
synchronously call error

### ISSUE THREAD

**Issue by ximlu** [vapor/sqlite-nio#70]
### Describe the issue

synchronously call error

### Vapor version

main

### Operating system and version

iOS

### Swift version

main

### Steps to reproduce

"I need to synchronously call the database within a certain function. I wrote the code like this: `_ = try dbp.query(sql).wait`. However, I received a NIO assertion error. I'm not sure if this is a bug in sqlite-nio, or if I'm using it incorrectly, or if sqlite-nio simply doesn't support synchronous read/write operations on the database."

    @usableFromInline
    internal func _preconditionSafeToWait(file: StaticString, line: UInt) {
        let explainer: () -> String = { """
BUG DETECTED: wait() must not be called when on an EventLoop.
Calling wait() on any EventLoop can lead to
- deadlocks
- stalling processing of other connections (Channels) that are handled on the EventLoop that wait was called on

Further information:
- current eventLoop: \(MultiThreadedEventLoopGroup.currentEventLoop.debugDescription)
- event loop associated to future: \(self)
"""
        }
        precondition(!self.inEventLoop, explainer(), file: file, line: line)
        precondition(MultiThreadedEventLoopGroup.currentEventLoop == nil, explainer(), file: file, line: line)
    }

**Comment by gwynne** [comment]
As you suggest, this is not supported. In SQLiteNIO's current design, database operations must occur on a thread pool for safety and are thus inherently asynchronous. A future design is expected to use Swift's support for `actor` types instead, but this will also be asynchronous in nature.
